using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ZeroAlloc.Cache.Generator;

internal static class CacheWriter
{
    public static void Write(SourceProductionContext ctx, CacheModel model)
    {
        var sb = new StringBuilder();

        WriteHeader(sb, model);

        // Namespace
        if (model.Namespace != null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // Proxy class
        WriteProxy(sb, model);
        sb.AppendLine();

        // Container-lifetime holder for the size-limited cache of the MaxEntries methods
        if (model.AnyMethodUsesIsolatedCache)
        {
            WriteBoundedCacheHolder(sb, model);
            sb.AppendLine();
        }

        // DI extension
        WriteDiExtension(sb, model);

        // Add source
        var hint = model.Namespace != null
            ? $"{model.Namespace}_{model.InterfaceName}.Cache.g.cs"
            : $"{model.InterfaceName}.Cache.g.cs";
        ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void WriteHeader(StringBuilder sb, CacheModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Extension-method usings: global:: qualifies type names but NOT extension methods.
        if (model.AnyMethodUsesIMemoryCache || model.AnyMethodUsesIsolatedCache)
        {
            sb.AppendLine("using Microsoft.Extensions.Caching.Memory;");
        }
        if (model.AnyMethodUsesHybridCache)
        {
            // AddHybridCache() is an extension on IServiceCollection in Microsoft.Extensions.Caching.Hybrid.
            sb.AppendLine("using Microsoft.Extensions.Caching.Hybrid;");
        }
        // AddTransient/AddMemoryCache extension methods. Unconditional: the DI extension is always
        // emitted, including for a proxy whose methods are all passthrough, so gating this on cache
        // usage leaves AddTransient/GetRequiredService unresolved (CS1061).
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        bool anyNonHybridCached = false;
        bool anyHybridCachedMethod = false;
        foreach (var m in model.CachedMethods)
        {
            if (!m.EffectiveConfig.UseHybridCache) anyNonHybridCached = true;
            else anyHybridCachedMethod = true;
        }

        if (anyNonHybridCached || anyHybridCachedMethod)
        {
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using System.Diagnostics.Metrics;");
            sb.AppendLine();
        }
    }

    private static string OptionsFieldName(string methodName) =>
        $"_{char.ToLowerInvariant(methodName[0])}{methodName.Substring(1)}Options";

    private static string BoundedCacheHolderName(string interfaceName) =>
        $"{interfaceName}BoundedCache";

    // Methods with MaxEntries > 0 use the isolated size-limited cache; every other non-hybrid
    // method uses the shared DI IMemoryCache, whatever else the interface declares. See #180.
    private static bool UsesBoundedCache(CachedMethodModel m) => m.UsesBoundedCache;

    private static string StripInterfacePrefix(string name)
    {
        if (name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]))
            return name.Substring(1);
        return name;
    }

    private static void WriteProxyFields(StringBuilder sb, string ifaceFqn, CacheModel model)
    {
        bool anyNonHybridCached = false;
        bool anyHybridCachedMethod = false;
        foreach (var m in model.CachedMethods)
        {
            if (!m.EffectiveConfig.UseHybridCache) anyNonHybridCached = true;
            else anyHybridCachedMethod = true;
        }

        WriteTelemetryFields(sb, anyNonHybridCached, anyHybridCachedMethod);

        sb.AppendLine($"    private readonly {ifaceFqn} _inner;");

        if (model.AnyMethodUsesIMemoryCache)
            sb.AppendLine("    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");

        // The bounded cache is owned by a DI singleton, not by the proxy: the proxy is transient,
        // so a per-instance cache started empty on every resolution. See #180.
        if (model.AnyMethodUsesIsolatedCache)
            sb.AppendLine("    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache _boundedCache;");

        if (model.AnyMethodUsesHybridCache)
            sb.AppendLine("    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;");

        sb.AppendLine();

        foreach (var m in model.CachedMethods)
        {
            if (!m.EffectiveConfig.UseHybridCache) continue;
            var fieldName = OptionsFieldName(m.Name);
            sb.AppendLine($"    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions {fieldName} =");
            sb.AppendLine($"        new() {{ Expiration = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs}) }};");
            sb.AppendLine();
        }
    }

    private static void WriteTelemetryFields(StringBuilder sb, bool anyNonHybridCached, bool anyHybridCachedMethod)
    {
        if (anyNonHybridCached || anyHybridCachedMethod)
        {
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Meter _meter =");
            sb.AppendLine($"        new(\"ZeroAlloc.Cache\");");
            sb.AppendLine($"    private static readonly global::System.Diagnostics.ActivitySource _activitySource =");
            sb.AppendLine($"        new(\"ZeroAlloc.Cache\");");
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _lookupDurationMs =");
            sb.AppendLine($"        _meter.CreateHistogram<double>(\"cache.lookup_duration_ms\");");
        }

        if (anyNonHybridCached)
        {
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hits =");
            sb.AppendLine($"        _meter.CreateCounter<long>(\"cache.hits\");");
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Counter<long> _misses =");
            sb.AppendLine($"        _meter.CreateCounter<long>(\"cache.misses\");");
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Counter<long> _evictions =");
            sb.AppendLine($"        _meter.CreateCounter<long>(\"cache.evictions\");");
        }

        if (anyHybridCachedMethod)
        {
            // HybridCache does not expose per-entry hit/miss; we count total factory invocations instead.
            sb.AppendLine($"    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hybridCalls =");
            sb.AppendLine($"        _meter.CreateCounter<long>(\"cache.hybrid_calls\");");
        }

        if (anyNonHybridCached || anyHybridCachedMethod)
        {
            sb.AppendLine();
        }
    }

    private static void WriteProxyConstructor(StringBuilder sb, string proxyName, string ifaceFqn, CacheModel model)
    {
        var parameters = new System.Collections.Generic.List<string> { $"{ifaceFqn} inner" };
        if (model.AnyMethodUsesIMemoryCache)
            parameters.Add("global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache");
        if (model.AnyMethodUsesIsolatedCache)
            parameters.Add($"{BoundedCacheHolderName(model.InterfaceName)} boundedCache");
        if (model.AnyMethodUsesHybridCache)
            parameters.Add("global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache");

        sb.AppendLine($"    public {proxyName}(");
        for (int i = 0; i < parameters.Count; i++)
            sb.AppendLine($"        {parameters[i]}{(i == parameters.Count - 1 ? ")" : ",")}");

        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        if (model.AnyMethodUsesIMemoryCache)
            sb.AppendLine("        _cache = cache;");
        if (model.AnyMethodUsesIsolatedCache)
            sb.AppendLine("        _boundedCache = boundedCache.Cache;");
        if (model.AnyMethodUsesHybridCache)
            sb.AppendLine("        _hybridCache = hybridCache;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteBoundedCacheHolder(StringBuilder sb, CacheModel model)
    {
        // A dedicated type rather than a static field: registered as a singleton by the generated
        // DI extension, it is shared by every proxy the container resolves, disposed with that
        // container, and never shared between containers.
        var holderName = BoundedCacheHolderName(model.InterfaceName);
        sb.AppendLine($"internal sealed class {holderName} : global::System.IDisposable");
        sb.AppendLine("{");
        sb.AppendLine("    public global::Microsoft.Extensions.Caching.Memory.MemoryCache Cache { get; } =");
        sb.AppendLine($"        new(new global::Microsoft.Extensions.Caching.Memory.MemoryCacheOptions {{ SizeLimit = {model.IsolatedCacheMaxEntries} }});");
        sb.AppendLine();
        sb.AppendLine("    public void Dispose() => Cache.Dispose();");
        sb.AppendLine("}");
    }

    private static void WriteProxy(StringBuilder sb, CacheModel model)
    {
        var proxyName = $"{model.InterfaceName}CacheProxy";
        var ifaceFqn = $"global::{model.InterfaceFqn}";

        sb.AppendLine($"internal sealed class {proxyName} : {ifaceFqn}");
        sb.AppendLine("{");

        WriteProxyFields(sb, ifaceFqn, model);
        WriteProxyConstructor(sb, proxyName, ifaceFqn, model);

        // Cached methods
        foreach (var m in model.CachedMethods)
        {
            if (m.EffectiveConfig.UseHybridCache)
                WriteHybridCachedMethod(sb, model.InterfaceName, m);
            else
                WriteCachedMethod(sb, model.InterfaceName, m);
        }

        // Passthrough methods
        foreach (var m in model.PassthroughMethods)
            WritePassthroughMethod(sb, m);

        sb.AppendLine("}");
    }

    private static void WriteCachedMethod(StringBuilder sb, string interfaceName, CachedMethodModel m)
    {
        var cacheMethodTag = $"{interfaceName}.{m.Name}";
        sb.AppendLine($"    public async {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine("    {");
        sb.AppendLine($"        using var __activity = _activitySource.StartActivity(\"cache.lookup\");");
        sb.AppendLine($"        __activity?.SetTag(\"cache.method\", \"{cacheMethodTag}\");");
        sb.AppendLine($"        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();");
        sb.AppendLine($"        var __key = $\"{interfaceName}.{m.Name}{m.KeyArguments}\";");
        var cacheField = UsesBoundedCache(m) ? "_boundedCache" : "_cache";
        var (hitCondition, hitReturn) = BuildCacheHit(m);
        sb.AppendLine($"        if ({cacheField}.TryGetValue(__key, out object? __boxed) && {hitCondition})");
        sb.AppendLine("        {");
        sb.AppendLine($"            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>(\"method\", \"{m.Name}\"));");
        sb.AppendLine($"            __activity?.SetTag(\"cache.tier\", \"L1\");");
        sb.AppendLine($"            __activity?.SetTag(\"cache.hit\", true);");
        sb.AppendLine($"            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,");
        sb.AppendLine($"                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"cache.method\", \"{cacheMethodTag}\"));");
        sb.AppendLine($"            return {hitReturn};");
        sb.AppendLine("        }");
        sb.AppendLine($"        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>(\"method\", \"{m.Name}\"));");
        sb.AppendLine($"        var __result = await _inner.{m.Name}({m.ArgumentList}).ConfigureAwait(false);");
        WriteCacheSetCall(sb, m, cacheField);
        sb.AppendLine($"        __activity?.SetTag(\"cache.tier\", \"L1\");");
        sb.AppendLine($"        __activity?.SetTag(\"cache.hit\", false);");
        sb.AppendLine($"        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,");
        sb.AppendLine($"            new global::System.Collections.Generic.KeyValuePair<string, object?>(\"cache.method\", \"{cacheMethodTag}\"));");
        sb.AppendLine("        return __result;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // The hit path reads the entry as object and tests it against the concrete return type.
    // It must not call the generic CacheExtensions.TryGetValue<TItem>: for a value-type return
    // TItem is Nullable<T>, and its `result is TItem` test never returns under NativeAOT unless
    // something else in the app happens to use Nullable<T>. That is an upstream runtime bug,
    // so this shape is a mitigation, not a simplification target: keep it until the runtime
    // fix ships. See https://github.com/ZeroAlloc-Net/ZeroAlloc.Cache/issues/182.
    // Unboxing a value type does not allocate, so this adds no allocation to the hit path.
    // A stored null is a hit for a nullable return, as it was with TryGetValue<TItem>.
    private static (string Condition, string Return) BuildCacheHit(CachedMethodModel m)
    {
        var underlying = m.InnerUnderlyingTypeFqn;
        if (m.InnerIsValueType && !m.InnerIsNullable)
            return ($"__boxed is {underlying} __cached", "__cached");

        // Nullable<T>: test and unbox as T, so no runtime cast or unbox ever targets Nullable<T>.
        if (m.InnerIsValueType)
            return ($"__boxed is null or {underlying}", $"__boxed is null ? default({underlying}?) : ({underlying})__boxed");

        // A cached null is returned as it was stored; '!' only where the return type is not annotated.
        var forgive = m.InnerIsNullable ? "" : "!";
        return ($"__boxed is null or {underlying}", $"({m.InnerReturnTypeFqn})__boxed{forgive}");
    }

    private static void WriteCacheSetCall(StringBuilder sb, CachedMethodModel m, string cacheField)
    {
        // The size-limited bounded cache rejects entries without a Size; the shared IMemoryCache
        // is not size-limited, so its entries carry none.
        bool isolated = UsesBoundedCache(m);
        // Always use MemoryCacheEntryOptions so we can attach the eviction callback.
        sb.AppendLine($"        {cacheField}.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions");

        if (m.EffectiveConfig.Sliding)
            sb.Append($"            {{ SlidingExpiration = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs})");
        else
            sb.Append($"            {{ AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs})");

        if (isolated)
            sb.AppendLine(", Size = 1 }");
        else
            sb.AppendLine(" }");

        sb.AppendLine($"            .RegisterPostEvictionCallback(static (_, _, _, _) =>");
        sb.AppendLine($"                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>(\"method\", \"{m.Name}\"))));");
    }

    private static void WriteHybridCachedMethod(StringBuilder sb, string interfaceName, CachedMethodModel m)
    {
        // Note: HybridCache.GetOrCreateAsync does not expose a separate hit/miss path.
        // We count _hybridCalls when the factory delegate is invoked (factory call = cache miss).
        // Eviction callbacks via MemoryCacheEntryOptions do not apply to HybridCache.
        var fieldName = OptionsFieldName(m.Name);
        var ctName = m.CancellationTokenParamName ?? "ct";
        var (state, lambda) = BuildHybridStateAndLambda(m, ctName);
        var ctArg = m.HasCancellationToken ? m.CancellationTokenParamName : "default";
        var cacheMethodTag = $"{interfaceName}.{m.Name}";

        // Method is emitted async so the activity scope spans the entire lookup. The original
        // shape was a sync method that returned the ValueTask directly; switching to async keeps
        // the same external contract but lets `using var __activity` and the duration capture
        // observe completion.
        sb.AppendLine($"    public async {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine("    {");
        sb.AppendLine($"        using var __activity = _activitySource.StartActivity(\"cache.lookup\");");
        sb.AppendLine($"        __activity?.SetTag(\"cache.method\", \"{cacheMethodTag}\");");
        sb.AppendLine($"        __activity?.SetTag(\"cache.tier\", \"L2\");");
        sb.AppendLine($"        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();");
        sb.AppendLine($"        try");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return await _hybridCache.GetOrCreateAsync(");
        sb.AppendLine($"                $\"{interfaceName}.{m.Name}{m.KeyArguments}\",");
        sb.AppendLine($"                {state},");
        sb.AppendLine($"                {lambda},");
        sb.AppendLine($"                {fieldName},");
        sb.AppendLine($"                cancellationToken: {ctArg}).ConfigureAwait(false);");
        sb.AppendLine($"        }}");
        sb.AppendLine($"        finally");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,");
        sb.AppendLine($"                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"cache.method\", \"{cacheMethodTag}\"));");
        sb.AppendLine($"        }}");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static (string State, string Lambda) BuildHybridStateAndLambda(CachedMethodModel m, string ctName)
    {
        var methodTag = $"new global::System.Collections.Generic.KeyValuePair<string, object?>(\"method\", \"{m.Name}\")";
        if (m.KeyParams.IsEmpty)
        {
            return (
                "_inner",
                $"static async (inner, {ctName}) => {{ _hybridCalls.Add(1, {methodTag}); return await inner.{m.Name}({ctName}).ConfigureAwait(false); }}");
        }

        var combinedSb = new System.Text.StringBuilder();
        var lambdaSb = new System.Text.StringBuilder();
        bool first = true;
        foreach (var kp in m.KeyParams)
        {
            if (!first) { combinedSb.Append(", "); lambdaSb.Append(", "); }
            first = false;
            combinedSb.Append(kp.Name).Append(": ").Append(kp.Name);
            lambdaSb.Append("s.").Append(kp.Name);
        }
        var state = $"(inner: _inner, {combinedSb})";

        if (m.HasCancellationToken)
        {
            if (!first) lambdaSb.Append(", ");
            lambdaSb.Append(ctName);
        }
        var lambda = $"static async (s, {ctName}) => {{ _hybridCalls.Add(1, {methodTag}); return await s.inner.{m.Name}({lambdaSb}).ConfigureAwait(false); }}";
        return (state, lambda);
    }

    private static void WritePassthroughMethod(StringBuilder sb, PassthroughMethodModel m)
    {
        sb.AppendLine($"    public {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine($"        => _inner.{m.Name}({m.ArgumentList});");
        sb.AppendLine();
    }

    private static void WriteDiExtension(StringBuilder sb, CacheModel model)
    {
        var ifaceFqn = $"global::{model.InterfaceFqn}";
        var proxyName = $"{model.InterfaceName}CacheProxy";
        var methodName = $"Add{StripInterfacePrefix(model.InterfaceName)}Cache";

        bool anyIMemoryCache = model.AnyMethodUsesIMemoryCache;
        bool anyHybridCache = model.AnyMethodUsesHybridCache;
        bool anyIsolated = model.AnyMethodUsesIsolatedCache;

        // CS0703: a public extension method cannot carry a generic constraint naming a less
        // accessible interface. Match the interface's accessibility instead (#120). The proxy
        // class is already internal, so only this pair needs adjusting.
        var access = model.IsPubliclyAccessible ? "public" : "internal";
        sb.AppendLine($"{access} static partial class CacheServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    {access} static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}<");
        // IL2091: TImpl flows into AddTransient<T> which requires PublicConstructors.
        // Without this annotation consumers' publish fails when they promote IL2091 to error.
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendLine("        TImpl>(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine($"        where TImpl : class, {ifaceFqn}");
        sb.AppendLine("    {");
        if (anyIMemoryCache)
            sb.AppendLine("        services.AddMemoryCache();");
        if (anyIsolated)
        {
            // Factory registration: the container disposes singletons it creates, but not
            // pre-built instances handed to it.
            var holderName = BoundedCacheHolderName(model.InterfaceName);
            sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions");
            sb.AppendLine($"            .TryAddSingleton<{holderName}>(services, static _ => new {holderName}());");
        }
        if (anyHybridCache)
            sb.AppendLine("        services.AddHybridCache();");
        sb.AppendLine("        services.AddTransient<TImpl>();");
        sb.AppendLine($"        services.AddTransient<{ifaceFqn}>(sp =>");
        WriteDiExtensionProxyCreation(sb, proxyName, model);
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void WriteDiExtensionProxyCreation(StringBuilder sb, string proxyName, CacheModel model)
    {
        // Must pass exactly the parameters WriteProxyConstructor declares, in the same order.
        var arguments = new System.Collections.Generic.List<string> { "sp.GetRequiredService<TImpl>()" };
        if (model.AnyMethodUsesIMemoryCache)
            arguments.Add("sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()");
        if (model.AnyMethodUsesIsolatedCache)
            arguments.Add($"sp.GetRequiredService<{BoundedCacheHolderName(model.InterfaceName)}>()");
        if (model.AnyMethodUsesHybridCache)
            arguments.Add("sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()");

        // Pure passthrough: constructor takes only inner
        if (arguments.Count == 1)
        {
            sb.AppendLine($"            new {proxyName}({arguments[0]}));");
            return;
        }

        sb.AppendLine($"            new {proxyName}(");
        for (int i = 0; i < arguments.Count; i++)
            sb.AppendLine($"                {arguments[i]}{(i == arguments.Count - 1 ? "));" : ",")}");
    }
}
