using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ZeroAlloc.Cache.Generator;

internal static class CacheWriter
{
    public static void Write(SourceProductionContext ctx, CacheModel model)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings required by extension methods used in the proxy body
        if (model.AnyMethodUsesIMemoryCache || model.AnyMethodUsesIsolatedCache)
        {
            sb.AppendLine("using Microsoft.Extensions.Caching.Memory;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
        }

        // Namespace
        if (model.Namespace != null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // Proxy class
        WriteProxy(sb, model);
        sb.AppendLine();

        // DI extension
        WriteDiExtension(sb, model);

        // Add source
        var hint = model.Namespace != null
            ? $"{model.Namespace}_{model.InterfaceName}.Cache.g.cs"
            : $"{model.InterfaceName}.Cache.g.cs";
        ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string OptionsFieldName(string methodName) =>
        $"_{char.ToLowerInvariant(methodName[0])}{methodName.Substring(1)}Options";

    private static string StripInterfacePrefix(string name)
    {
        if (name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]))
            return name.Substring(1);
        return name;
    }

    private static void WriteProxyFields(StringBuilder sb, string ifaceFqn, CacheModel model)
    {
        sb.AppendLine($"    private readonly {ifaceFqn} _inner;");

        if (model.AnyMethodUsesIsolatedCache)
            sb.AppendLine($"    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache _cache =");
        else if (model.AnyMethodUsesIMemoryCache)
            sb.AppendLine("    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");

        if (model.AnyMethodUsesIsolatedCache)
            sb.AppendLine($"        new(new global::Microsoft.Extensions.Caching.Memory.MemoryCacheOptions {{ SizeLimit = {model.IsolatedCacheMaxEntries} }});");

        if (model.AnyMethodUsesHybridCache)
            sb.AppendLine("    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;");

        sb.AppendLine();

        foreach (var m in model.CachedMethods)
        {
            if (!m.EffectiveConfig.UseHybridCache) continue;
            var fieldName = OptionsFieldName(m.Name);
            sb.AppendLine($"    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions {fieldName} =");
            sb.AppendLine($"        new() {{ Expiration = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs}) }};");
            sb.AppendLine();
        }
    }

    private static void WriteProxyConstructor(StringBuilder sb, string proxyName, string ifaceFqn, CacheModel model)
    {
        bool needsIMemoryCache = model.AnyMethodUsesIMemoryCache && !model.AnyMethodUsesIsolatedCache;
        bool needsHybridCache = model.AnyMethodUsesHybridCache;

        sb.AppendLine($"    public {proxyName}(");

        if (needsIMemoryCache && needsHybridCache)
        {
            sb.AppendLine($"        {ifaceFqn} inner,");
            sb.AppendLine("        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache,");
            sb.AppendLine("        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)");
        }
        else if (needsIMemoryCache)
        {
            sb.AppendLine($"        {ifaceFqn} inner,");
            sb.AppendLine("        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache)");
        }
        else if (needsHybridCache)
        {
            sb.AppendLine($"        {ifaceFqn} inner,");
            sb.AppendLine("        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)");
        }
        else
        {
            sb.AppendLine($"        {ifaceFqn} inner)");
        }

        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        if (needsIMemoryCache)
            sb.AppendLine("        _cache = cache;");
        if (needsHybridCache)
            sb.AppendLine("        _hybridCache = hybridCache;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteProxy(StringBuilder sb, CacheModel model)
    {
        var proxyName = $"{model.InterfaceName}CacheProxy";
        var ifaceFqn = $"global::{model.InterfaceFqn}";

        sb.AppendLine($"internal sealed class {proxyName} : {ifaceFqn}");
        sb.AppendLine("{");

        WriteProxyFields(sb, ifaceFqn, model);
        WriteProxyConstructor(sb, proxyName, ifaceFqn, model);

        // Cached methods
        foreach (var m in model.CachedMethods)
        {
            if (m.EffectiveConfig.UseHybridCache)
                WriteHybridCachedMethod(sb, model.InterfaceName, m);
            else
                WriteCachedMethod(sb, model.InterfaceName, m);
        }

        // Passthrough methods
        foreach (var m in model.PassthroughMethods)
            WritePassthroughMethod(sb, m);

        sb.AppendLine("}");
    }

    private static void WriteCachedMethod(StringBuilder sb, string interfaceName, CachedMethodModel m)
    {
        sb.AppendLine($"    public async {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __key = $\"{interfaceName}.{m.Name}{m.KeyArguments}\";");
        sb.AppendLine($"        if (_cache.TryGetValue(__key, out {m.InnerReturnTypeFqn}? __cached))");
        sb.AppendLine("            return __cached!;");
        sb.AppendLine($"        var __result = await _inner.{m.Name}({m.ArgumentList}).ConfigureAwait(false);");
        WriteCacheSetCall(sb, m);
        sb.AppendLine("        return __result;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteCacheSetCall(StringBuilder sb, CachedMethodModel m)
    {
        bool isolated = m.EffectiveConfig.MaxEntries > 0;
        if (isolated || m.EffectiveConfig.Sliding)
        {
            sb.AppendLine($"        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions");
            if (m.EffectiveConfig.Sliding)
                sb.Append($"            {{ SlidingExpiration = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs})");
            else
                sb.Append($"            {{ AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs})");
            if (isolated)
                sb.AppendLine(", Size = 1 });");
            else
                sb.AppendLine(" });");
        }
        else
        {
            sb.AppendLine($"        _cache.Set(__key, __result, global::System.TimeSpan.FromMilliseconds({m.EffectiveConfig.TtlMs}));");
        }
    }

    private static void WriteHybridCachedMethod(StringBuilder sb, string interfaceName, CachedMethodModel m)
    {
        var fieldName = OptionsFieldName(m.Name);

        var ctName = m.CancellationTokenParamName ?? "ct";

        string state;
        string lambda;
        if (m.KeyParams.IsEmpty)
        {
            state = "_inner";
            lambda = $"static async (inner, {ctName}) => await inner.{m.Name}({ctName}).ConfigureAwait(false)";
        }
        else
        {
            var combinedSb = new System.Text.StringBuilder();
            var lambdaSb = new System.Text.StringBuilder();
            bool first = true;
            foreach (var kp in m.KeyParams)
            {
                if (!first) { combinedSb.Append(", "); lambdaSb.Append(", "); }
                first = false;
                combinedSb.Append(kp.Name).Append(": ").Append(kp.Name);
                lambdaSb.Append("s.").Append(kp.Name);
            }
            state = $"(inner: _inner, {combinedSb})";

            if (m.HasCancellationToken)
            {
                if (!first) lambdaSb.Append(", ");
                lambdaSb.Append(ctName);
            }
            lambda = $"static async (s, {ctName}) => await s.inner.{m.Name}({lambdaSb}).ConfigureAwait(false)";
        }

        var ctArg = m.HasCancellationToken ? m.CancellationTokenParamName : "default";

        sb.AppendLine($"    public {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine("    {");
        sb.AppendLine("        return _hybridCache.GetOrCreateAsync(");
        sb.AppendLine($"            $\"{interfaceName}.{m.Name}{m.KeyArguments}\",");
        sb.AppendLine($"            {state},");
        sb.AppendLine($"            {lambda},");
        sb.AppendLine($"            {fieldName},");
        sb.AppendLine($"            cancellationToken: {ctArg});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WritePassthroughMethod(StringBuilder sb, PassthroughMethodModel m)
    {
        sb.AppendLine($"    public {m.ReturnTypeFqn} {m.Name}({m.ParameterList})");
        sb.AppendLine($"        => _inner.{m.Name}({m.ArgumentList});");
        sb.AppendLine();
    }

    private static void WriteDiExtension(StringBuilder sb, CacheModel model)
    {
        var ifaceFqn = $"global::{model.InterfaceFqn}";
        var proxyName = $"{model.InterfaceName}CacheProxy";
        var methodName = $"Add{StripInterfacePrefix(model.InterfaceName)}Cache";

        bool anyIMemoryCache = model.AnyMethodUsesIMemoryCache;
        bool anyHybridCache = model.AnyMethodUsesHybridCache;
        bool anyIsolated = model.AnyMethodUsesIsolatedCache;

        sb.AppendLine("public static partial class CacheServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}<");
        // IL2091: TImpl flows into AddTransient<T> which requires PublicConstructors.
        // Without this annotation consumers' publish fails when they promote IL2091 to error.
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendLine("        TImpl>(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine($"        where TImpl : class, {ifaceFqn}");
        sb.AppendLine("    {");
        if (anyIMemoryCache && !anyIsolated)
            sb.AppendLine("        services.AddMemoryCache();");
        if (anyHybridCache)
            sb.AppendLine("        services.AddHybridCache();");
        sb.AppendLine("        services.AddTransient<TImpl>();");
        sb.AppendLine($"        services.AddTransient<{ifaceFqn}>(sp =>");
        WriteDiExtensionProxyCreation(sb, proxyName, anyIMemoryCache, anyHybridCache, anyIsolated);
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void WriteDiExtensionProxyCreation(
        StringBuilder sb,
        string proxyName,
        bool anyIMemoryCache,
        bool anyHybridCache,
        bool anyIsolated)
    {
        // Pure passthrough (no cached methods) or isolated-only: constructor takes only inner
        if (!anyIMemoryCache && !anyHybridCache)
        {
            sb.AppendLine($"            new {proxyName}(sp.GetRequiredService<TImpl>()));");
            return;
        }

        sb.AppendLine($"            new {proxyName}(");
        sb.AppendLine("                sp.GetRequiredService<TImpl>(),");

        if (anyIMemoryCache && anyHybridCache)
        {
            sb.AppendLine("                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>(),");
            sb.AppendLine("                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));");
        }
        else if (anyIMemoryCache)
        {
            sb.AppendLine("                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()));");
        }
        else
        {
            sb.AppendLine("                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));");
        }
    }
}
