//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache _cache =
        new(new global::Microsoft.Extensions.Caching.Memory.MemoryCacheOptions { SizeLimit = 500 });
    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;

    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions _findAsyncOptions =
        new() { Expiration = global::System.TimeSpan.FromMilliseconds(10000) };

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)
    {
        _inner = inner;
        _hybridCache = hybridCache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        var __key = $"IMyService.GetAsync:{id}";
        if (_cache.TryGetValue(__key, out string? __cached))
            return __cached!;
        var __result = await _inner.GetAsync(id, ct).ConfigureAwait(false);
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000), Size = 1 });
        return __result;
    }

    public global::System.Threading.Tasks.ValueTask<string> FindAsync(string query, global::System.Threading.CancellationToken ct)
    {
        return _hybridCache.GetOrCreateAsync(
            $"IMyService.FindAsync:{query}",
            (inner: _inner, query: query),
            static async (s, ct) => await s.inner.FindAsync(s.query, ct).ConfigureAwait(false),
            _findAsyncOptions,
            cancellationToken: ct);
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddHybridCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));
        return services;
    }
}
