//HintName: IGlobalService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

internal sealed class IGlobalServiceCacheProxy : global::IGlobalService
{
    private readonly global::IGlobalService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;

    public IGlobalServiceCacheProxy(
        global::IGlobalService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache)
    {
        _inner = inner;
        _cache = cache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(int id, global::System.Threading.CancellationToken ct)
    {
        var __key = $"IGlobalService.GetAsync:{id}";
        if (_cache.TryGetValue(__key, out string? __cached))
            return __cached!;
        var __result = await _inner.GetAsync(id, ct).ConfigureAwait(false);
        _cache.Set(__key, __result, global::System.TimeSpan.FromMilliseconds(5000));
        return __result;
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGlobalServiceCache<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::IGlobalService
    {
        services.AddMemoryCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::IGlobalService>(sp =>
            new IGlobalServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()));
        return services;
    }
}
