//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache)
    {
        _inner = inner;
        _cache = cache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        var __key = $"IMyService.GetAsync:{id}";
        if (_cache.TryGetValue(__key, out string? __cached))
            return __cached!;
        var __result = await _inner.GetAsync(id, ct).ConfigureAwait(false);
        _cache.Set(__key, __result, global::System.TimeSpan.FromMilliseconds(30000));
        return __result;
    }

    public global::System.Threading.Tasks.ValueTask SaveAsync(string data, global::System.Threading.CancellationToken ct)
        => _inner.SaveAsync(data, ct);

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddMemoryCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()));
        return services;
    }
}
