//HintName: T.IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private static readonly global::System.Diagnostics.Metrics.Meter _meter =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.ActivitySource _activitySource =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _lookupDurationMs =
        _meter.CreateHistogram<double>("cache.lookup_duration_ms");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hits =
        _meter.CreateCounter<long>("cache.hits");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _misses =
        _meter.CreateCounter<long>("cache.misses");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _evictions =
        _meter.CreateCounter<long>("cache.evictions");

    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;
    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache? _memoryCache;

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache)
    {
        _inner = inner;
        _cache = cache;
        _memoryCache = cache.GetType() == typeof(global::Microsoft.Extensions.Caching.Memory.MemoryCache)
            ? (global::Microsoft.Extensions.Caching.Memory.MemoryCache)cache
            : null;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetByIdAsync(string id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.GetByIdAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.GetByIdAsync:{id}", out __boxed);
        if (__found && __boxed is null or string)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetByIdAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetByIdAsync"));
            return (string)__boxed!;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetByIdAsync"));
        var __result = await _inner.GetByIdAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.GetByIdAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetByIdAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetByIdAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, string id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.GetByIdAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.GetByIdAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetBySlugAsync(string slug, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.GetBySlugAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, slug, out __boxed)
            : _cache.TryGetValue($"IMyService.GetBySlugAsync:{slug}", out __boxed);
        if (__found && __boxed is null or string)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetBySlugAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetBySlugAsync"));
            return (string)__boxed!;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetBySlugAsync"));
        var __result = await _inner.GetBySlugAsync(slug, ct).ConfigureAwait(false);
        var __key = $"IMyService.GetBySlugAsync:{slug}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(5000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetBySlugAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetBySlugAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, string slug, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.GetBySlugAsync:{slug}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.GetBySlugAsync:{slug}", out __value);
        }
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddMemoryCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()));
        return services;
    }
}
