//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private static readonly global::System.Diagnostics.Metrics.Meter _meter =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.ActivitySource _activitySource =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _lookupDurationMs =
        _meter.CreateHistogram<double>("cache.lookup_duration_ms");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hits =
        _meter.CreateCounter<long>("cache.hits");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _misses =
        _meter.CreateCounter<long>("cache.misses");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _evictions =
        _meter.CreateCounter<long>("cache.evictions");

    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;
    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache _boundedCache;

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache,
        IMyServiceBoundedCache boundedCache)
    {
        _inner = inner;
        _cache = cache;
        _boundedCache = boundedCache.Cache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.GetAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var __key = $"IMyService.GetAsync:{id}";
        if (_cache.TryGetValue(__key, out object? __boxed) && __boxed is null or string)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetAsync"));
            return (string)__boxed!;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"));
        var __result = await _inner.GetAsync(id, ct).ConfigureAwait(false);
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetAsync"));
        return __result;
    }

    public async global::System.Threading.Tasks.ValueTask<int> CountAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.CountAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var __key = $"IMyService.CountAsync:{id}";
        if (_boundedCache.TryGetValue((object)__key, out object? __boxed) && __boxed is int __cached)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.CountAsync"));
            return __cached;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"));
        var __result = await _inner.CountAsync(id, ct).ConfigureAwait(false);
        _boundedCache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000), Size = 1 }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.CountAsync"));
        return __result;
    }

}

internal sealed class IMyServiceBoundedCache : global::System.IDisposable
{
    public global::Microsoft.Extensions.Caching.Memory.MemoryCache Cache { get; } =
        new(new global::Microsoft.Extensions.Caching.Memory.MemoryCacheOptions { SizeLimit = 100 });

    public void Dispose() => Cache.Dispose();
}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddMemoryCache();
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions
            .TryAddSingleton<IMyServiceBoundedCache>(services, static _ => new IMyServiceBoundedCache());
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>(),
                sp.GetRequiredService<IMyServiceBoundedCache>()));
        return services;
    }
}
