//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private static readonly global::System.Diagnostics.Metrics.Meter _meter =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.ActivitySource _activitySource =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _lookupDurationMs =
        _meter.CreateHistogram<double>("cache.lookup_duration_ms");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hits =
        _meter.CreateCounter<long>("cache.hits");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _misses =
        _meter.CreateCounter<long>("cache.misses");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _evictions =
        _meter.CreateCounter<long>("cache.evictions");

    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;
    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache? _memoryCache;
    private readonly global::Microsoft.Extensions.Caching.Memory.MemoryCache _boundedCache;

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache,
        IMyServiceBoundedCache boundedCache)
    {
        _inner = inner;
        _cache = cache;
        _memoryCache = cache.GetType() == typeof(global::Microsoft.Extensions.Caching.Memory.MemoryCache)
            ? (global::Microsoft.Extensions.Caching.Memory.MemoryCache)cache
            : null;
        _boundedCache = boundedCache.Cache;
    }

    public async global::System.Threading.Tasks.ValueTask<int> CountAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.CountAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.CountAsync:{id}", out __boxed);
        if (__found && __boxed is int __cached)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.CountAsync"));
            return __cached;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"));
        var __result = await _inner.CountAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.CountAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "CountAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.CountAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.CountAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.CountAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.Task<int?> MaybeCountAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.MaybeCountAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.MaybeCountAsync:{id}", out __boxed);
        if (__found && __boxed is null or int)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeCountAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeCountAsync"));
            return __boxed is null ? default(int?) : (int)__boxed;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeCountAsync"));
        var __result = await _inner.MaybeCountAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.MaybeCountAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeCountAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeCountAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.MaybeCountAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.MaybeCountAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.ValueTask<global::T.Money> TotalAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.TotalAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.TotalAsync:{id}", out __boxed);
        if (__found && __boxed is global::T.Money __cached)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "TotalAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.TotalAsync"));
            return __cached;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "TotalAsync"));
        var __result = await _inner.TotalAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.TotalAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "TotalAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.TotalAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.TotalAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.TotalAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.ValueTask<global::T.Money?> MaybeTotalAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.MaybeTotalAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.MaybeTotalAsync:{id}", out __boxed);
        if (__found && __boxed is null or global::T.Money)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeTotalAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeTotalAsync"));
            return __boxed is null ? default(global::T.Money?) : (global::T.Money)__boxed;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeTotalAsync"));
        var __result = await _inner.MaybeTotalAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.MaybeTotalAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeTotalAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeTotalAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.MaybeTotalAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.MaybeTotalAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.ValueTask<string?> MaybeNameAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.MaybeNameAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = _memoryCache is not null
            ? __TryGetBySpanKey(_memoryCache, id, out __boxed)
            : _cache.TryGetValue($"IMyService.MaybeNameAsync:{id}", out __boxed);
        if (__found && __boxed is null or string)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeNameAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeNameAsync"));
            return (string?)__boxed;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeNameAsync"));
        var __result = await _inner.MaybeNameAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.MaybeNameAsync:{id}";
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "MaybeNameAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.MaybeNameAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.MaybeNameAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.MaybeNameAsync:{id}", out __value);
        }
    }

    public async global::System.Threading.Tasks.ValueTask<int> BoundedCountAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.BoundedCountAsync");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        object? __boxed;
        bool __found = __TryGetBySpanKey(_boundedCache, id, out __boxed);
        if (__found && __boxed is int __cached)
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "BoundedCountAsync"));
            __activity?.SetTag("cache.tier", "L1");
            __activity?.SetTag("cache.hit", true);
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.BoundedCountAsync"));
            return __cached;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "BoundedCountAsync"));
        var __result = await _inner.BoundedCountAsync(id, ct).ConfigureAwait(false);
        var __key = $"IMyService.BoundedCountAsync:{id}";
        _boundedCache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000), Size = 1 }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "BoundedCountAsync"))));
        __activity?.SetTag("cache.tier", "L1");
        __activity?.SetTag("cache.hit", false);
        _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
            new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.BoundedCountAsync"));
        return __result;

        static bool __TryGetBySpanKey(global::Microsoft.Extensions.Caching.Memory.MemoryCache __cache, int id, out object? __value)
        {
            global::System.Span<char> __buffer = stackalloc char[256];
            return global::System.MemoryExtensions.TryWrite(__buffer, $"IMyService.BoundedCountAsync:{id}", out int __length)
                ? __cache.TryGetValue((global::System.ReadOnlySpan<char>)__buffer.Slice(0, __length), out __value)
                : __cache.TryGetValue((object)$"IMyService.BoundedCountAsync:{id}", out __value);
        }
    }

}

internal sealed class IMyServiceBoundedCache : global::System.IDisposable
{
    public global::Microsoft.Extensions.Caching.Memory.MemoryCache Cache { get; } =
        new(new global::Microsoft.Extensions.Caching.Memory.MemoryCacheOptions { SizeLimit = 100 });

    public void Dispose() => Cache.Dispose();
}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddMemoryCache();
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions
            .TryAddSingleton<IMyServiceBoundedCache>(services, static _ => new IMyServiceBoundedCache());
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>(),
                sp.GetRequiredService<IMyServiceBoundedCache>()));
        return services;
    }
}
