//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Hybrid;
using Microsoft.Extensions.DependencyInjection;

using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private static readonly global::System.Diagnostics.Metrics.Meter _meter =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.ActivitySource _activitySource =
        new("ZeroAlloc.Cache");
    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _lookupDurationMs =
        _meter.CreateHistogram<double>("cache.lookup_duration_ms");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hybridCalls =
        _meter.CreateCounter<long>("cache.hybrid_calls");

    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;

    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions _getAsyncOptions =
        new() { Expiration = global::System.TimeSpan.FromMilliseconds(1000) };

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)
    {
        _inner = inner;
        _hybridCache = hybridCache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(global::System.Threading.CancellationToken ct)
    {
        using var __activity = _activitySource.StartActivity("cache.lookup");
        __activity?.SetTag("cache.method", "IMyService.GetAsync");
        __activity?.SetTag("cache.tier", "L2");
        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        try
        {
            return await _hybridCache.GetOrCreateAsync(
                $"IMyService.GetAsync",
                _inner,
                static async (inner, ct) => { _hybridCalls.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync")); return await inner.GetAsync(ct).ConfigureAwait(false); },
                _getAsyncOptions,
                cancellationToken: ct).ConfigureAwait(false);
        }
        finally
        {
            _lookupDurationMs.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds,
                new global::System.Collections.Generic.KeyValuePair<string, object?>("cache.method", "IMyService.GetAsync"));
        }
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddHybridCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));
        return services;
    }
}
