//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;

    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions _getAsyncOptions =
        new() { Expiration = global::System.TimeSpan.FromMilliseconds(1000) };

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)
    {
        _inner = inner;
        _hybridCache = hybridCache;
    }

    public global::System.Threading.Tasks.ValueTask<string> GetAsync(global::System.Threading.CancellationToken ct)
    {
        return _hybridCache.GetOrCreateAsync(
            $"IMyService.GetAsync",
            _inner,
            static async (inner, ct) => await inner.GetAsync(ct).ConfigureAwait(false),
            _getAsyncOptions,
            cancellationToken: ct);
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddHybridCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));
        return services;
    }
}
