//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;

    public IMyServiceCacheProxy(
        global::T.IMyService inner)
    {
        _inner = inner;
    }

    public global::System.Threading.Tasks.ValueTask SaveAsync(string data, global::System.Threading.CancellationToken ct)
        => _inner.SaveAsync(data, ct);

    public global::System.Threading.Tasks.ValueTask DeleteAsync(int id, global::System.Threading.CancellationToken ct)
        => _inner.DeleteAsync(id, ct);

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));
        return services;
    }
}
