//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

using System.Diagnostics.Metrics;

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private static readonly global::System.Diagnostics.Metrics.Meter _meter =
        new("zeroalloc.cache");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _hits =
        _meter.CreateCounter<long>("cache.hits");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _misses =
        _meter.CreateCounter<long>("cache.misses");
    private static readonly global::System.Diagnostics.Metrics.Counter<long> _evictions =
        _meter.CreateCounter<long>("cache.evictions");

    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache)
    {
        _inner = inner;
        _cache = cache;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        var __key = $"IMyService.GetAsync:{id}";
        if (_cache.TryGetValue(__key, out string? __cached))
        {
            _hits.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"));
            return __cached!;
        }
        _misses.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"));
        var __result = await _inner.GetAsync(id, ct).ConfigureAwait(false);
        _cache.Set(__key, __result, new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions
            { AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromMilliseconds(30000) }
            .RegisterPostEvictionCallback(static (_, _, _, _) =>
                _evictions.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("method", "GetAsync"))));
        return __result;
    }

    public global::System.Threading.Tasks.ValueTask SaveAsync(string data, global::System.Threading.CancellationToken ct)
        => _inner.SaveAsync(data, ct);

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddMemoryCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Memory.IMemoryCache>()));
        return services;
    }
}
