//HintName: T_IMyService.Cache.g.cs
// <auto-generated/>
#nullable enable

namespace T;

internal sealed class IMyServiceCacheProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _hybridCache;

    private static readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCacheEntryOptions _getAsyncOptions =
        new() { Expiration = global::System.TimeSpan.FromMilliseconds(30000) };

    public IMyServiceCacheProxy(
        global::T.IMyService inner,
        global::Microsoft.Extensions.Caching.Hybrid.HybridCache hybridCache)
    {
        _inner = inner;
        _hybridCache = hybridCache;
    }

    public global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        return _hybridCache.GetOrCreateAsync(
            $"IMyService.GetAsync:{id}",
            (inner: _inner, id: id),
            static async (s, ct) => await s.inner.GetAsync(s.id, ct).ConfigureAwait(false),
            _getAsyncOptions,
            cancellationToken: ct);
    }

}

public static partial class CacheServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceCache<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddHybridCache();
        services.AddTransient<TImpl>();
        services.AddTransient<global::T.IMyService>(sp =>
            new IMyServiceCacheProxy(
                sp.GetRequiredService<TImpl>(),
                sp.GetRequiredService<global::Microsoft.Extensions.Caching.Hybrid.HybridCache>()));
        return services;
    }
}
